import Foundation

/// Puts `bigbro` on PATH, pointing at the interpreter inside the app.
///
/// Someone who installed from the DMG has a complete Python and a complete MLX
/// stack on disk already; asking them to `uv tool install` a second copy to get
/// `bigbro pair approve` would be absurd. This writes a three-line shim instead.
///
/// `~/.local/bin` rather than `/usr/local/bin`: the latter is root-owned, does
/// not exist on a clean install, and creating it needs either a privileged helper
/// or an installer package — an entire extra signing and lifecycle surface for
/// what is ultimately a convenience symlink. `~/.local/bin` needs no
/// authorisation and is already on PATH for anyone using uv or pipx.
public enum CommandLineTool {
    public static var destination: URL {
        URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent(".local/bin/bigbro")
    }

    public enum Status: Equatable, Sendable {
        case notInstalled
        /// Installed and pointing at this copy of the app.
        case current
        /// Installed, but pointing somewhere else — usually an app that moved.
        case stale(pointingAt: String)
    }

    /// The shim, generated from wherever the app actually is.
    ///
    /// Never hardcodes /Applications: an app run from ~/Downloads or a build
    /// directory should install a shim that works, not one that points at a path
    /// nobody has.
    static func script(forInterpreter interpreter: String) -> String {
        """
        #!/bin/sh
        # Generated by BigBro.app. Runs the daemon bundled inside it.
        exec "\(interpreter)" -m bigbro "$@"
        """
    }

    /// The interpreter inside the running app, if there is one.
    public static func bundledInterpreter(
        resources: URL? = Bundle.main.resourceURL,
        fileManager: FileManager = .default
    ) -> String? {
        guard let resources else { return nil }
        let python = resources.appendingPathComponent("python/bin/python3").path
        return fileManager.isExecutableFile(atPath: python) ? python : nil
    }

    public static func status(
        at destination: URL = CommandLineTool.destination,
        interpreter: String? = bundledInterpreter(),
        fileManager: FileManager = .default
    ) -> Status {
        guard let existing = try? String(contentsOf: destination, encoding: .utf8) else {
            return .notInstalled
        }
        guard let interpreter, existing.contains(interpreter) else {
            // Find what it does point at, so the UI can say "reinstall" rather
            // than leaving the user to wonder why their shim broke.
            let pointsAt = existing
                .split(separator: "\n")
                .first { $0.hasPrefix("exec ") }
                .map(String.init) ?? "something else"
            return .stale(pointingAt: pointsAt)
        }
        return .current
    }

    @discardableResult
    public static func install(
        at destination: URL = CommandLineTool.destination,
        interpreter: String? = bundledInterpreter(),
        fileManager: FileManager = .default
    ) throws -> URL {
        guard let interpreter else {
            throw CocoaError(.fileNoSuchFile)
        }
        try fileManager.createDirectory(
            at: destination.deletingLastPathComponent(), withIntermediateDirectories: true
        )
        try script(forInterpreter: interpreter).write(to: destination, atomically: true, encoding: .utf8)
        try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: destination.path)
        return destination
    }

    /// Whether `~/.local/bin` is somewhere the user's shell will actually look.
    ///
    /// Installing a shim into a directory that is not on PATH looks like success
    /// and behaves like failure, so the UI needs to be able to say so.
    public static func destinationIsOnPath(
        environment: [String: String] = ProcessInfo.processInfo.environment
    ) -> Bool {
        let directory = destination.deletingLastPathComponent().path
        return (environment["PATH"] ?? "").split(separator: ":").contains { $0 == directory }
    }
}
